#name="Bala"
#print(name[::-1])
users=["tom","john","sara","bala",'Bala']
data=['tom',32,'true']
empty=['ddd']
print("divya" in users)
print(users[3])
#print(users[::-1])
#users.append(data)
#print(users)
#print(users.index('bala'))
#print(users[0:2])
#print(users[1:])
#print(users[-2:-1])
#print(len(data))
#users.append('vela')
#print(users)
#newusers=['divya','vela']
#users.append(newusers)
#print(users)
#users.extend(['rob','jimmy'])
#print(users)
#users.extend(data)
#print(users)
#users.insert(0,'mani')
#print(users)
#users[2:2]=['bharathi','rithya']
#print(users)
#users[1:2]=['anu','mukan']
#print(users)
#users.remove('mani')
#print(users)
#users.pop()
#print(users)
#del users[1]
#print(users)
#del empty
#empty.clear()
#print(empty)
#users[1:2]=['tom']
#users.sort()
#print(users)
#users.sort(key=str.upper)
#print(users)
#print(len(users))
num=[1,0,56,2,8]
#num.reverse()
#print(num)
#num.sort(reverse=False)
#print(num)
#num.sort()
#print(num)
#num.insert(1,'hai')
#print(num)
#num.remove('hai')
#print(num)
numscopy=num.copy()
mynum=list(num)
mycopy=num[:]
print(numscopy)
print(mynum)
mycopy.sort()
print(mycopy)
print(num)
